1- operators:
            - arithmetic operators: + - * / %
            - comparison operators: == != > < <= >=
            - logical operators: && || !
            - increment & decrement: ++ --

2- selection statement:
            - if statement
            - else statement
            - if else statement
            - switch statement

3- iteration statement:
            - for loop
            - while loop
            - do while loop
            -// infinite loop
