1- functions:
            - declaration 
            - definition 
            - call Function
            - void Function = procedure 

2- strings:
            - concatenate strings
            - access string using index   stringName[0] / stringName.at[0]
            - getline

3- Scopes:
            - local scope / global scope
            = Local scope variables are only visible and usable within a specific function.
            = Block scope variables are only visible and usable within a specific block (a set of curly braces).
            = Global scope variables are visible and usable anywhere in the program
            
