1-  Arrays:
           - intro
           - declare
           - add values
           - access values
           - update values
           - print values

2- Pointers:
           - intro
           - create
           - print value using variables or pointers (dereference pointer)
           - update value using pointers
           - using NULL with pointers

3- References:
           - intro & create
           - update value using Reference
